version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "npm install && node app.js"
